import { CreditCard } from "./types";

// ============================================================================
// Seed data — 32 realistic Indian credit cards (2026).
// Figures are reasonable real-world approximations for guidance/education,
// NOT official bank terms. Reward `rate` = effective ₹ value per ₹1 spent.
// ============================================================================

export const CARDS: CreditCard[] = [
  // ---------------- Cashback / Lifetime-free ----------------
  {
    id: "amazon-pay-icici", slug: "amazon-pay-icici", name: "Amazon Pay", bank: "ICICI Bank",
    network: ["Visa"], category: "Cashback", tier: "Entry", color: "#0f9d96",
    joiningFee: 0, annualFee: 0, annualFeeWaiver: 0,
    baseRate: 0.01, rewardCurrency: "Amazon Pay Balance", pointValue: 1,
    rewardRules: [
      { category: "online", rate: 0.05 },
      { category: "bills", rate: 0.02 },
      { category: "dining", rate: 0.02 },
    ],
    minIncomeAnnual: 250000, minCreditScore: 720, minAge: 18,
    loungeVisitsDomestic: 0, loungeVisitsIntl: 0, forexMarkup: 3.5,
    welcomeBonusValue: 0, welcomeBonusDesc: "No joining fee, ever.",
    benefits: ["5% back on Amazon (Prime members)", "2% on bill payments", "1% fuel surcharge waiver"],
    bestFor: ["Amazon shoppers", "First card", "No-fee seekers"],
    summary: "The single best lifetime-free card for anyone who shops on Amazon. 5% back with Prime, no fee ever, rewards as instant Amazon Pay balance.",
    pros: ["No annual fee, lifetime", "Strong 5% Amazon reward", "Instant, simple redemption"],
    cons: ["Best value locked to Amazon", "No lounge access", "Invite-based approval"],
  },
  {
    id: "sbi-cashback", slug: "cashback-sbi", name: "Cashback SBI", bank: "SBI Card",
    network: ["Visa", "RuPay"], category: "Cashback", tier: "Mid", color: "#1e50a2",
    joiningFee: 999, annualFee: 999, annualFeeWaiver: 200000,
    baseRate: 0.01, rewardCurrency: "Cashback", pointValue: 1,
    rewardRules: [{ category: "online", rate: 0.05, monthlyCapValue: 5000 }],
    minIncomeAnnual: 300000, minCreditScore: 720, minAge: 18,
    loungeVisitsDomestic: 0, loungeVisitsIntl: 0, forexMarkup: 3.5,
    welcomeBonusValue: 0, welcomeBonusDesc: "Fee reversed on ₹2L annual spend.",
    benefits: ["5% cashback on all online spends", "1% offline", "Auto-credited cashback"],
    bestFor: ["Online shoppers", "Simplicity"],
    summary: "5% cashback on every online spend with no merchant restriction — the simplest high-value online card in India.",
    pros: ["Merchant-agnostic 5% online", "Auto-credited cashback", "Reasonable fee with waiver"],
    cons: ["₹5,000 monthly cap on bonus", "No lounge or travel perks"],
  },
  {
    id: "axis-ace", slug: "axis-ace", name: "ACE", bank: "Axis Bank",
    network: ["Visa"], category: "Cashback", tier: "Entry", color: "#97144d",
    joiningFee: 499, annualFee: 499, annualFeeWaiver: 200000,
    baseRate: 0.015, rewardCurrency: "Cashback", pointValue: 1,
    rewardRules: [
      { category: "bills", rate: 0.05 },
      { category: "dining", rate: 0.04 },
      { category: "online", rate: 0.04 },
      { category: "upi", rate: 0.02 },
    ],
    minIncomeAnnual: 300000, minCreditScore: 700, minAge: 18,
    loungeVisitsDomestic: 4, loungeVisitsIntl: 0, forexMarkup: 3.5,
    welcomeBonusValue: 0, welcomeBonusDesc: "Fee reversed on ₹2L annual spend.",
    benefits: ["5% on bills via Google Pay", "4% on Swiggy/Zomato/Ola", "1.5% flat everywhere"],
    bestFor: ["Bill payers", "Flat cashback", "Everyday use"],
    summary: "A flat 1.5% on everything with 5% on utility bills and 4% on food delivery. One of the best all-rounder cashback cards at its fee.",
    pros: ["High flat base rate", "Strong on bills & dining", "4 lounge visits"],
    cons: ["Bonus categories tied to Google Pay", "Markup on forex"],
  },
  {
    id: "kiwi-rupay", slug: "kiwi-rupay", name: "Kiwi RuPay", bank: "Kiwi (Federal/Axis)",
    network: ["RuPay"], category: "Cashback", tier: "Entry", color: "#15a34a",
    joiningFee: 0, annualFee: 0, annualFeeWaiver: 0,
    baseRate: 0.01, rewardCurrency: "Kiwi Coins", pointValue: 1,
    rewardRules: [{ category: "upi", rate: 0.04 }, { category: "online", rate: 0.02 }],
    minIncomeAnnual: 200000, minCreditScore: 700, minAge: 18,
    loungeVisitsDomestic: 0, loungeVisitsIntl: 0, forexMarkup: 3.5,
    welcomeBonusValue: 0, welcomeBonusDesc: "Lifetime free.",
    benefits: ["Rewards on UPI spends", "Scan-and-pay via RuPay", "No annual fee"],
    bestFor: ["UPI-first users", "Students", "No-fee seekers"],
    summary: "Rare card that rewards UPI/QR spends — pairs perfectly with a cashback card for full coverage.",
    pros: ["Rewards on UPI", "Lifetime free", "Easy approval"],
    cons: ["Lower base reward", "RuPay-only acceptance abroad"],
  },

  // ---------------- Student / Entry ----------------
  {
    id: "sbi-simplyclick", slug: "sbi-simplyclick", name: "SimplyCLICK", bank: "SBI Card",
    network: ["Visa"], category: "Student", tier: "Entry", color: "#2563c9",
    joiningFee: 499, annualFee: 499, annualFeeWaiver: 100000,
    baseRate: 0.0025, rewardCurrency: "Reward Points", pointValue: 0.25,
    rewardRules: [{ category: "online", rate: 0.025 }],
    minIncomeAnnual: 250000, minCreditScore: 700, minAge: 18,
    loungeVisitsDomestic: 0, loungeVisitsIntl: 0, forexMarkup: 3.5,
    welcomeBonusValue: 500, welcomeBonusDesc: "₹500 Amazon voucher on joining.",
    benefits: ["10x points on Amazon, BookMyShow, Cleartrip", "Milestone vouchers"],
    bestFor: ["First-time users", "Students", "Online beginners"],
    summary: "An easy entry-level online card with 10x points on popular partners and a low fee.",
    pros: ["Low fee & easy approval", "Online accelerated points", "Welcome voucher"],
    cons: ["Low base rate", "Points worth less than cashback"],
  },
  {
    id: "hdfc-moneyback-plus", slug: "hdfc-moneyback-plus", name: "MoneyBack+", bank: "HDFC Bank",
    network: ["Visa"], category: "Student", tier: "Entry", color: "#2b7de9",
    joiningFee: 500, annualFee: 500, annualFeeWaiver: 50000,
    baseRate: 0.01, rewardCurrency: "Reward Points", pointValue: 0.25,
    rewardRules: [{ category: "online", rate: 0.04 }, { category: "dining", rate: 0.02 }, { category: "groceries", rate: 0.02 }],
    minIncomeAnnual: 250000, minCreditScore: 700, minAge: 18,
    loungeVisitsDomestic: 0, loungeVisitsIntl: 0, forexMarkup: 3.5,
    welcomeBonusValue: 500, welcomeBonusDesc: "500 reward points on fee payment.",
    benefits: ["10x points on Amazon, Flipkart, Swiggy, BigBasket", "Low fee"],
    bestFor: ["Beginners", "Everyday spends"],
    summary: "Low-fee everyday card with 10x points on common online merchants. A solid first HDFC card.",
    pros: ["Cheap to hold", "Accelerated online points", "Easy upgrade path"],
    cons: ["Modest point value", "Caps on accelerated points"],
  },

  // ---------------- Shopping / Co-brand ----------------
  {
    id: "flipkart-axis", slug: "flipkart-axis", name: "Flipkart Axis", bank: "Axis Bank",
    network: ["Mastercard"], category: "Shopping", tier: "Mid", color: "#2874f0",
    joiningFee: 500, annualFee: 500, annualFeeWaiver: 350000,
    baseRate: 0.01, rewardCurrency: "Cashback", pointValue: 1,
    rewardRules: [{ category: "online", rate: 0.05 }, { category: "dining", rate: 0.04 }, { category: "travel", rate: 0.04 }],
    minIncomeAnnual: 300000, minCreditScore: 700, minAge: 18,
    loungeVisitsDomestic: 4, loungeVisitsIntl: 0, forexMarkup: 3.5,
    welcomeBonusValue: 1100, welcomeBonusDesc: "Welcome benefits worth ~₹1,100.",
    benefits: ["5% on Flipkart & Cleartrip", "4% on preferred merchants", "1.5% elsewhere"],
    bestFor: ["Flipkart regulars", "Online shopping"],
    summary: "5% unlimited cashback on Flipkart plus 4% on preferred partners — the default card for Flipkart-heavy shoppers.",
    pros: ["Strong Flipkart reward", "Decent flat rate", "Lounge access"],
    cons: ["Best value tied to Flipkart ecosystem"],
  },
  {
    id: "tata-neu-plus-hdfc", slug: "tata-neu-plus-hdfc", name: "Tata Neu Plus", bank: "HDFC Bank",
    network: ["RuPay", "Visa"], category: "Co-brand", tier: "Entry", color: "#69169e",
    joiningFee: 499, annualFee: 499, annualFeeWaiver: 100000,
    baseRate: 0.01, rewardCurrency: "NeuCoins", pointValue: 1,
    rewardRules: [
      { category: "online", rate: 0.05 },
      { category: "groceries", rate: 0.04 },
      { category: "bills", rate: 0.03 },
      { category: "upi", rate: 0.01, monthlyCapValue: 500 },
    ],
    minIncomeAnnual: 300000, minCreditScore: 700, minAge: 18,
    loungeVisitsDomestic: 4, loungeVisitsIntl: 0, forexMarkup: 3.5,
    welcomeBonusValue: 499, welcomeBonusDesc: "499 NeuCoins on first transaction.",
    benefits: ["Up to 7% NeuCoins on Tata brands", "BigBasket, Croma, Westside", "UPI rewards on RuPay"],
    bestFor: ["Tata brand shoppers", "Grocery & UPI"],
    summary: "Base Tata Neu card — up to 7% NeuCoins across Tata brands (BigBasket, Croma, Westside), with rewards even on UPI.",
    pros: ["Strong Tata ecosystem rewards", "UPI earning", "Low fee"],
    cons: ["Value tied to Tata brands", "NeuCoin redemption limited to Tata Neu"],
  },
  {
    id: "tata-neu-infinity-hdfc", slug: "tata-neu-infinity-hdfc", name: "Tata Neu Infinity", bank: "HDFC Bank",
    network: ["RuPay", "Visa"], category: "Co-brand", tier: "Mid", color: "#8211c7",
    joiningFee: 1499, annualFee: 1499, annualFeeWaiver: 300000,
    baseRate: 0.015, rewardCurrency: "NeuCoins", pointValue: 1,
    rewardRules: [
      { category: "online", rate: 0.05 },
      { category: "groceries", rate: 0.05 },
      { category: "bills", rate: 0.05 },
      { category: "upi", rate: 0.015, monthlyCapValue: 500 },
    ],
    minIncomeAnnual: 300000, minCreditScore: 720, minAge: 18,
    loungeVisitsDomestic: 8, loungeVisitsIntl: 4, forexMarkup: 2,
    welcomeBonusValue: 1499, welcomeBonusDesc: "1,499 NeuCoins on first transaction.",
    benefits: ["Up to 10% NeuCoins on Tata brands", "1.5% on all else incl. UPI", "Lounge access + low forex"],
    bestFor: ["Tata loyalists", "Higher spenders", "Grocery & bills"],
    summary: "Premium Tata Neu card — up to 10% NeuCoins on Tata brands, 1.5% everywhere (even UPI), with lounge access and a low 2% forex markup.",
    pros: ["Highest Tata-brand rewards", "1.5% base incl. UPI", "Lounge + low forex"],
    cons: ["Higher fee", "Value still tilted to Tata ecosystem"],
  },

  // ---------------- Rewards (mid) ----------------
  {
    id: "hdfc-millennia", slug: "hdfc-millennia", name: "Millennia", bank: "HDFC Bank",
    network: ["Visa", "Mastercard"], category: "Rewards", tier: "Mid", color: "#1f6feb",
    joiningFee: 1000, annualFee: 1000, annualFeeWaiver: 100000,
    baseRate: 0.01, rewardCurrency: "Cashback", pointValue: 1,
    rewardRules: [
      { category: "online", rate: 0.05, monthlyCapValue: 1000 },
      { category: "dining", rate: 0.05, monthlyCapValue: 1000 },
      { category: "groceries", rate: 0.05 },
      { category: "entertainment", rate: 0.05 },
      { category: "travel", rate: 0.05 },
    ],
    minIncomeAnnual: 420000, minCreditScore: 720, minAge: 21,
    loungeVisitsDomestic: 8, loungeVisitsIntl: 0, forexMarkup: 3.5,
    verified: true, verifiedOn: "2026-06-27", officialUrl: "https://www.hdfcbank.com/personal/pay/cards/credit-cards/millennia-credit-card",
    welcomeBonusValue: 1000, welcomeBonusDesc: "1,000 cashpoints on fee payment.",
    benefits: ["5% cashback on Amazon, Flipkart, Swiggy, Zomato", "1% on everything", "Quarterly lounge access"],
    bestFor: ["Online + dining", "Young professionals"],
    summary: "5% cashback on the biggest online brands and 1% on everything else — a versatile mid-tier workhorse.",
    pros: ["Broad 5% online coverage", "Lounge access", "Recognisable brand value"],
    cons: ["Monthly caps on bonus", "Forex markup high"],
  },
  {
    id: "icici-rubyx", slug: "icici-rubyx", name: "Rubyx", bank: "ICICI Bank",
    network: ["Mastercard", "Diners"], category: "Rewards", tier: "Mid", color: "#e0586a",
    joiningFee: 3000, annualFee: 3000, annualFeeWaiver: 0,
    baseRate: 0.015, rewardCurrency: "Reward Points", pointValue: 0.4,
    rewardRules: [{ category: "dining", rate: 0.04 }, { category: "groceries", rate: 0.04 }, { category: "online", rate: 0.03 }],
    minIncomeAnnual: 800000, minCreditScore: 730, minAge: 21,
    loungeVisitsDomestic: 8, loungeVisitsIntl: 2, forexMarkup: 3.5,
    welcomeBonusValue: 5000, welcomeBonusDesc: "Welcome vouchers worth ~₹5,000.",
    benefits: ["Accelerated dining & grocery", "Domestic + intl lounge", "Dual cards (MC + Diners)"],
    bestFor: ["Grocery & dining", "Mid-premium seekers"],
    summary: "A quiet workhorse for households spending ₹15k+/month on groceries and dining, with a solid lounge stack.",
    pros: ["Strong grocery/dining", "Two networks", "Good lounge access"],
    cons: ["No fee waiver", "Average point value"],
  },

  // ---------------- Fuel ----------------
  {
    id: "bpcl-sbi-octane", slug: "bpcl-sbi-octane", name: "BPCL SBI Octane", bank: "SBI Card",
    network: ["Visa"], category: "Fuel", tier: "Mid", color: "#f0801a",
    joiningFee: 1499, annualFee: 1499, annualFeeWaiver: 200000,
    baseRate: 0.01, rewardCurrency: "Reward Points", pointValue: 0.25,
    rewardRules: [
      { category: "fuel", rate: 0.075 },
      { category: "dining", rate: 0.025 },
      { category: "groceries", rate: 0.025 },
      { category: "entertainment", rate: 0.025 },
    ],
    minIncomeAnnual: 300000, minCreditScore: 720, minAge: 21,
    loungeVisitsDomestic: 4, loungeVisitsIntl: 0, forexMarkup: 3.5,
    welcomeBonusValue: 1500, welcomeBonusDesc: "₹1,500 worth bonus points on joining.",
    benefits: ["7.25% value on BPCL fuel", "Fuel surcharge waiver", "Lounge access"],
    bestFor: ["Heavy commuters", "BPCL users"],
    summary: "The strongest fuel card in India — 7.25% value at BPCL pumps, ideal for high monthly fuel spends.",
    pros: ["Class-leading fuel reward", "Surcharge waiver", "Lounge access"],
    cons: ["Best value locked to BPCL", "Low base point value"],
  },
  {
    id: "iocl-hdfc", slug: "indianoil-hdfc", name: "IndianOil HDFC", bank: "HDFC Bank",
    network: ["RuPay", "Visa"], category: "Fuel", tier: "Entry", color: "#e8730c",
    joiningFee: 500, annualFee: 500, annualFeeWaiver: 50000,
    baseRate: 0.01, rewardCurrency: "Fuel Points", pointValue: 0.5,
    rewardRules: [{ category: "fuel", rate: 0.05 }, { category: "groceries", rate: 0.025 }, { category: "bills", rate: 0.025 }],
    minIncomeAnnual: 250000, minCreditScore: 700, minAge: 21,
    loungeVisitsDomestic: 0, loungeVisitsIntl: 0, forexMarkup: 3.5,
    welcomeBonusValue: 0, welcomeBonusDesc: "Low joining fee.",
    benefits: ["5% value at IndianOil pumps", "Fuel surcharge waiver", "UPI on RuPay"],
    bestFor: ["IOC-first drivers", "Low-fee fuel"],
    summary: "Best value at IndianOil outlets with a low fee — a budget-friendly fuel card for IOC regulars.",
    pros: ["Cheap to hold", "Good IOC fuel value", "UPI rewards on RuPay"],
    cons: ["Value tied to IndianOil", "No lounge"],
  },

  // ---------------- Travel ----------------
  {
    id: "scapia-federal", slug: "scapia-federal", name: "Scapia", bank: "Federal Bank",
    network: ["Visa"], category: "Travel", tier: "Mid", color: "#1ea7a0",
    joiningFee: 0, annualFee: 0, annualFeeWaiver: 0,
    baseRate: 0.02, rewardCurrency: "Scapia Coins", pointValue: 1,
    rewardRules: [{ category: "travel", rate: 0.1 }, { category: "dining", rate: 0.1 }, { category: "international", rate: 0.02 }],
    minIncomeAnnual: 400000, minCreditScore: 720, minAge: 18,
    loungeVisitsDomestic: 4, loungeVisitsIntl: 0, forexMarkup: 0,
    welcomeBonusValue: 0, welcomeBonusDesc: "Lifetime free.",
    benefits: ["10% back on travel & dining", "Zero forex markup", "Unlimited lounge on spends"],
    bestFor: ["Travellers", "Forex-free spends", "No-fee premium feel"],
    summary: "A lifetime-free travel card with 10% back on travel & dining and zero forex markup — punches well above its (non-existent) fee.",
    pros: ["Zero forex markup", "10% travel/dining", "No annual fee"],
    cons: ["Rewards redeemable via Scapia app", "Newer issuer"],
  },
  {
    id: "axis-atlas", slug: "axis-atlas", name: "Atlas", bank: "Axis Bank",
    network: ["Visa"], category: "Travel", tier: "Premium", color: "#0b132b",
    joiningFee: 5000, annualFee: 5000, annualFeeWaiver: 0,
    baseRate: 0.02, rewardCurrency: "EDGE Miles", pointValue: 1,
    rewardRules: [{ category: "travel", rate: 0.05 }, { category: "dining", rate: 0.04 }, { category: "international", rate: 0.04 }],
    minIncomeAnnual: 900000, minCreditScore: 740, minAge: 21,
    loungeVisitsDomestic: 12, loungeVisitsIntl: 8, forexMarkup: 1.5,
    welcomeBonusValue: 5000, welcomeBonusDesc: "2,500 EDGE Miles on joining.",
    benefits: ["EDGE Miles with transfer partners", "Unlimited lounge access", "Milestone miles"],
    bestFor: ["Frequent flyers", "Miles collectors"],
    summary: "A travel-first card with strong airline/hotel transfer partners and generous lounge access for frequent flyers.",
    pros: ["Good transfer partners", "Strong lounge stack", "Low forex"],
    cons: ["No fee waiver", "Best value needs transfers"],
  },
  {
    id: "icici-sapphiro", slug: "icici-sapphiro", name: "Sapphiro", bank: "ICICI Bank",
    network: ["Visa", "Amex"], category: "Travel", tier: "Premium", color: "#1b3a6b",
    joiningFee: 6500, annualFee: 3500, annualFeeWaiver: 0,
    baseRate: 0.013, rewardCurrency: "Reward Points", pointValue: 0.4,
    rewardRules: [{ category: "dining", rate: 0.04 }, { category: "travel", rate: 0.04 }, { category: "international", rate: 0.03 }],
    minIncomeAnnual: 900000, minCreditScore: 740, minAge: 21,
    loungeVisitsDomestic: 8, loungeVisitsIntl: 4, forexMarkup: 3.5,
    welcomeBonusValue: 9000, welcomeBonusDesc: "Vouchers worth ~₹9,000 across brands.",
    benefits: ["Travel & dining rewards", "Dual network cards", "BookMyShow benefits"],
    bestFor: ["Travel & dining", "Lifestyle perks"],
    summary: "A premium-lite travel and dining card with a rich welcome bonus and dual-network cards.",
    pros: ["Big welcome value", "Two networks", "Lounge access"],
    cons: ["High forex markup", "Modest point value"],
  },

  // ---------------- Premium ----------------
  {
    id: "hdfc-regalia-gold", slug: "hdfc-regalia-gold", name: "Regalia Gold", bank: "HDFC Bank",
    network: ["Visa", "Mastercard"], category: "Premium", tier: "Premium", color: "#a9701f",
    joiningFee: 2500, annualFee: 2500, annualFeeWaiver: 400000,
    baseRate: 0.013, rewardCurrency: "Reward Points", pointValue: 0.5,
    rewardRules: [{ category: "dining", rate: 0.05 }, { category: "travel", rate: 0.05 }, { category: "online", rate: 0.05 }, { category: "groceries", rate: 0.05 }],
    minIncomeAnnual: 1800000, minCreditScore: 750, minAge: 21,
    loungeVisitsDomestic: 12, loungeVisitsIntl: 6, forexMarkup: 2,
    verified: true, verifiedOn: "2026-06-27", officialUrl: "https://www.hdfcbank.com/personal/pay/cards/credit-cards/regalia-gold-credit-card",
    welcomeBonusValue: 2500, welcomeBonusDesc: "Gift voucher worth ₹2,500 on joining.",
    benefits: ["5x points on M&S, Reliance, Myntra, Nykaa", "12 domestic lounge visits", "Travel concierge"],
    bestFor: ["Premium lifestyle", "Travel & dining"],
    summary: "A well-rounded premium card with 5x points on lifestyle brands, strong lounge access, and a manageable fee with waiver.",
    pros: ["Versatile 5x categories", "Generous lounge", "Achievable fee waiver"],
    cons: ["High income bar", "Best redemption via SmartBuy"],
  },
  {
    id: "sbi-prime", slug: "sbi-prime", name: "PRIME", bank: "SBI Card",
    network: ["Visa", "Mastercard", "Amex"], category: "Premium", tier: "Premium", color: "#13315c",
    joiningFee: 2999, annualFee: 2999, annualFeeWaiver: 300000,
    baseRate: 0.013, rewardCurrency: "Reward Points", pointValue: 0.25,
    rewardRules: [{ category: "dining", rate: 0.05 }, { category: "groceries", rate: 0.05 }, { category: "entertainment", rate: 0.05 }, { category: "bills", rate: 0.025 }],
    minIncomeAnnual: 600000, minCreditScore: 740, minAge: 21,
    loungeVisitsDomestic: 8, loungeVisitsIntl: 4, forexMarkup: 3.5,
    welcomeBonusValue: 3000, welcomeBonusDesc: "₹3,000 e-voucher on joining.",
    benefits: ["5x on dining, groceries, movies", "Unlimited domestic lounge", "Milestone benefits"],
    bestFor: ["Families", "Dining & groceries"],
    summary: "A premium everyday card with 5x points on dining, groceries and movies, plus unlimited domestic lounge access.",
    pros: ["Strong everyday categories", "Unlimited domestic lounge", "Lower income bar"],
    cons: ["Low point value", "Forex markup high"],
  },

  // ---------------- Super-premium ----------------
  {
    id: "axis-magnus", slug: "axis-magnus", name: "Magnus", bank: "Axis Bank",
    network: ["Mastercard"], category: "Premium", tier: "Super-premium", color: "#5b2a86",
    joiningFee: 12500, annualFee: 12500, annualFeeWaiver: 2500000,
    baseRate: 0.012, rewardCurrency: "EDGE Reward Points", pointValue: 0.5,
    rewardRules: [{ category: "travel", rate: 0.05 }, { category: "dining", rate: 0.05 }, { category: "international", rate: 0.05 }],
    minIncomeAnnual: 1800000, minCreditScore: 760, minAge: 21,
    loungeVisitsDomestic: 99, loungeVisitsIntl: 8, forexMarkup: 2,
    welcomeBonusValue: 12500, welcomeBonusDesc: "Welcome voucher offsets fee.",
    benefits: ["2–5x value via transfer partners", "Unlimited lounge", "Milestone vouchers"],
    bestFor: ["High spenders ₹3L+/mo", "Travel maximisers"],
    summary: "For very high spenders, near-unbeatable travel transfer value and unlimited lounge access — one card to rule them all.",
    pros: ["Excellent transfer value", "Unlimited lounge", "High welcome value"],
    cons: ["Very high fee", "Waiver needs ₹25L spend"],
  },
  {
    id: "hdfc-infinia", slug: "hdfc-infinia-metal", name: "Infinia Metal", bank: "HDFC Bank",
    network: ["Visa", "Diners"], category: "Premium", tier: "Super-premium", color: "#2f3640",
    joiningFee: 12500, annualFee: 12500, annualFeeWaiver: 1000000,
    baseRate: 0.033, rewardCurrency: "Reward Points", pointValue: 1,
    rewardRules: [{ category: "travel", rate: 0.05 }, { category: "dining", rate: 0.05 }, { category: "online", rate: 0.05 }, { category: "international", rate: 0.05 }],
    minIncomeAnnual: 2500000, minCreditScore: 770, minAge: 21,
    loungeVisitsDomestic: 99, loungeVisitsIntl: 99, forexMarkup: 2,
    welcomeBonusValue: 12500, welcomeBonusDesc: "Welcome benefits offset the fee.",
    benefits: ["3.3% base, up to 16.5% via SmartBuy", "Unlimited global lounge", "Concierge"],
    bestFor: ["HNI", "Travel & lifestyle maximisers"],
    summary: "HDFC's flagship — 3.3% base value scaling to 16.5% via SmartBuy, with unlimited global lounge access. Invite-only.",
    pros: ["Best-in-class base value", "Unlimited global lounge", "Top redemption flexibility"],
    cons: ["Invite-only", "Very high income bar"],
  },
  {
    id: "icici-emeralde-private", slug: "icici-emeralde-private-metal", name: "Emeralde Private Metal", bank: "ICICI Bank",
    network: ["Visa", "Amex"], category: "Premium", tier: "Super-premium", color: "#0d4f3c",
    joiningFee: 12499, annualFee: 12499, annualFeeWaiver: 1000000,
    baseRate: 0.03, rewardCurrency: "Reward Points", pointValue: 1,
    rewardRules: [{ category: "travel", rate: 0.05 }, { category: "dining", rate: 0.04 }, { category: "international", rate: 0.04 }],
    minIncomeAnnual: 3000000, minCreditScore: 770, minAge: 21,
    loungeVisitsDomestic: 99, loungeVisitsIntl: 99, forexMarkup: 2,
    welcomeBonusValue: 12500, welcomeBonusDesc: "EaseMyTrip & Tata CLiQ vouchers.",
    benefits: ["3% on regular spends", "100% point redemption for travel via iShop", "Golf & concierge"],
    bestFor: ["HNI", "Simplicity at the top end"],
    summary: "ICICI's super-premium answer to Infinia — a strong 3% flat reward with full travel redemption via iShop.",
    pros: ["High flat reward", "Full travel redemption", "Unlimited lounge"],
    cons: ["Very high income bar", "High fee"],
  },
  {
    id: "idfc-first-select", slug: "idfc-first-wealth", name: "FIRST Wealth", bank: "IDFC First",
    network: ["Visa"], category: "Rewards", tier: "Premium", color: "#b8123c",
    joiningFee: 0, annualFee: 0, annualFeeWaiver: 0,
    baseRate: 0.025, rewardCurrency: "Reward Points", pointValue: 0.25,
    rewardRules: [{ category: "dining", rate: 0.025 }, { category: "online", rate: 0.025 }, { category: "travel", rate: 0.025 }],
    minIncomeAnnual: 600000, minCreditScore: 730, minAge: 21,
    loungeVisitsDomestic: 16, loungeVisitsIntl: 0, forexMarkup: 1.5,
    welcomeBonusValue: 0, welcomeBonusDesc: "Lifetime free.",
    benefits: ["Up to 10x points on high spends", "Quarterly lounge access", "Low forex markup"],
    bestFor: ["No-fee premium feel", "Everyday rewards"],
    summary: "A rare lifetime-free card with a premium feel — accelerated points on high spends, lounge access, and low forex.",
    pros: ["No annual fee", "Lounge + low forex", "High base on big spends"],
    cons: ["Lower point value", "Accelerated tiers need high spend"],
  },

  // ---------------- More breadth (fill to 32) ----------------
  {
    id: "au-lit", slug: "au-lit", name: "LIT", bank: "AU Small Finance", network: ["Visa"],
    category: "Cashback", tier: "Entry", color: "#7c3aed",
    joiningFee: 0, annualFee: 0, annualFeeWaiver: 0,
    baseRate: 0.01, rewardCurrency: "Cashback", pointValue: 1,
    rewardRules: [{ category: "online", rate: 0.02 }, { category: "dining", rate: 0.02 }],
    minIncomeAnnual: 300000, minCreditScore: 700, minAge: 18,
    loungeVisitsDomestic: 2, loungeVisitsIntl: 0, forexMarkup: 3.5,
    welcomeBonusValue: 0, welcomeBonusDesc: "Customisable feature packs.",
    benefits: ["Switch on/off reward features", "Pay only for what you use", "Lifetime free base"],
    bestFor: ["Customisation", "Low usage"],
    summary: "A modular card where you toggle reward 'features' on or off — flexible for light, variable spenders.",
    pros: ["Lifetime-free base", "Pay-per-feature", "Flexible"],
    cons: ["Value depends on active features", "Caps on packs"],
  },
  {
    id: "hsbc-platinum", slug: "hsbc-platinum", name: "Platinum", bank: "HSBC", network: ["Visa"],
    category: "Rewards", tier: "Entry", color: "#db0011",
    joiningFee: 0, annualFee: 0, annualFeeWaiver: 0,
    baseRate: 0.013, rewardCurrency: "Reward Points", pointValue: 0.25,
    rewardRules: [{ category: "dining", rate: 0.03 }, { category: "online", rate: 0.02 }],
    minIncomeAnnual: 400000, minCreditScore: 720, minAge: 18,
    loungeVisitsDomestic: 0, loungeVisitsIntl: 0, forexMarkup: 3.5,
    welcomeBonusValue: 1000, welcomeBonusDesc: "Vouchers on early spends.",
    benefits: ["Lifetime free", "Accelerated dining", "Milestone vouchers"],
    bestFor: ["No-fee rewards", "Dining"],
    summary: "A dependable lifetime-free rewards card with accelerated dining and milestone vouchers.",
    pros: ["No fee", "Good dining reward", "Easy redemption"],
    cons: ["No lounge", "Modest base"],
  },
  {
    id: "onecard", slug: "onecard", name: "OneCard", bank: "OneCard (BoB/SBM)", network: ["Visa"],
    category: "Rewards", tier: "Entry", color: "#1f1f1f",
    joiningFee: 0, annualFee: 0, annualFeeWaiver: 0,
    baseRate: 0.0025, rewardCurrency: "Reward Points", pointValue: 0.25,
    rewardRules: [{ category: "online", rate: 0.0125 }, { category: "dining", rate: 0.0125 }],
    minIncomeAnnual: 300000, minCreditScore: 700, minAge: 18,
    loungeVisitsDomestic: 0, loungeVisitsIntl: 0, forexMarkup: 1,
    welcomeBonusValue: 0, welcomeBonusDesc: "Metal card, lifetime free.",
    benefits: ["5x on top spend category", "Full app control", "Low forex markup"],
    bestFor: ["App-first users", "Low forex"],
    summary: "A sleek, app-first metal card that lifetime-free users love — 5x on your top monthly category, low forex.",
    pros: ["Lifetime free metal card", "Dynamic 5x category", "Great app"],
    cons: ["Low base rate", "Points value modest"],
  },
  {
    id: "amex-mrcc", slug: "amex-membership-rewards", name: "Membership Rewards", bank: "American Express", network: ["Amex"],
    category: "Rewards", tier: "Mid", color: "#016fd0",
    joiningFee: 1000, annualFee: 4500, annualFeeWaiver: 0,
    baseRate: 0.01, rewardCurrency: "Membership Rewards", pointValue: 0.5,
    rewardRules: [{ category: "dining", rate: 0.025 }, { category: "online", rate: 0.025 }],
    minIncomeAnnual: 600000, minCreditScore: 740, minAge: 18,
    loungeVisitsDomestic: 0, loungeVisitsIntl: 0, forexMarkup: 3.5,
    welcomeBonusValue: 4000, welcomeBonusDesc: "Milestone bonus points worth ~₹4,000.",
    benefits: ["Strong milestone bonuses", "18,000 bonus points on milestones", "Premium customer service"],
    bestFor: ["Milestone chasers", "Amex ecosystem"],
    summary: "Amex's entry rewards card — modest base but excellent milestone bonuses for steady monthly spenders.",
    pros: ["Great milestone value", "Premium service", "Good transfer partners"],
    cons: ["Limited acceptance", "High forex"],
  },
  {
    id: "rbl-shoprite", slug: "rbl-shoprite", name: "ShopRite", bank: "RBL Bank", network: ["Mastercard"],
    category: "Shopping", tier: "Entry", color: "#e11d48",
    joiningFee: 500, annualFee: 500, annualFeeWaiver: 100000,
    baseRate: 0.0025, rewardCurrency: "Reward Points", pointValue: 0.2,
    rewardRules: [{ category: "groceries", rate: 0.025 }, { category: "fuel", rate: 0.025 }],
    minIncomeAnnual: 250000, minCreditScore: 700, minAge: 18,
    loungeVisitsDomestic: 0, loungeVisitsIntl: 0, forexMarkup: 3.5,
    welcomeBonusValue: 0, welcomeBonusDesc: "Low fee.",
    benefits: ["Accelerated grocery points", "Fuel surcharge waiver"],
    bestFor: ["Grocery", "Budget shoppers"],
    summary: "An entry grocery card with accelerated points on supermarket spends and fuel surcharge waiver.",
    pros: ["Cheap", "Grocery focus"],
    cons: ["Low base", "Limited perks"],
  },
  {
    id: "standard-chartered-ultimate", slug: "sc-ultimate", name: "Ultimate", bank: "Standard Chartered", network: ["Visa"],
    category: "Premium", tier: "Super-premium", color: "#0473ea",
    joiningFee: 5000, annualFee: 5000, annualFeeWaiver: 0,
    baseRate: 0.033, rewardCurrency: "Reward Points", pointValue: 1,
    rewardRules: [{ category: "dining", rate: 0.033 }, { category: "travel", rate: 0.033 }, { category: "international", rate: 0.033 }],
    minIncomeAnnual: 1500000, minCreditScore: 760, minAge: 21,
    loungeVisitsDomestic: 99, loungeVisitsIntl: 8, forexMarkup: 2,
    welcomeBonusValue: 6000, welcomeBonusDesc: "Bonus points worth ~₹6,000.",
    benefits: ["3.3% on almost all spends", "Unlimited domestic lounge", "Golf access"],
    bestFor: ["Flat high reward", "Simplicity"],
    summary: "A super-premium card prized for a 3.3% reward on nearly all spends, regardless of category.",
    pros: ["High flat reward", "Unlimited lounge", "Broad earning"],
    cons: ["Weaker redemption options", "High fee"],
  },
  {
    id: "yes-marquee", slug: "yes-marquee", name: "Marquee", bank: "YES Bank", network: ["Visa"],
    category: "Premium", tier: "Premium", color: "#0a3d62",
    joiningFee: 9999, annualFee: 4999, annualFeeWaiver: 1000000,
    baseRate: 0.024, rewardCurrency: "Reward Points", pointValue: 0.25,
    rewardRules: [{ category: "online", rate: 0.05 }, { category: "dining", rate: 0.05 }, { category: "international", rate: 0.04 }],
    minIncomeAnnual: 2000000, minCreditScore: 760, minAge: 21,
    loungeVisitsDomestic: 99, loungeVisitsIntl: 6, forexMarkup: 1,
    welcomeBonusValue: 10000, welcomeBonusDesc: "Welcome vouchers ~₹10,000.",
    benefits: ["High reward on online & dining", "Unlimited lounge", "Low 1% forex"],
    bestFor: ["High online spenders", "Low forex travel"],
    summary: "A premium card with strong online/dining rewards, unlimited lounge and a market-low 1% forex markup.",
    pros: ["Low forex", "Strong online reward", "Unlimited lounge"],
    cons: ["High fee", "Modest point value"],
  },
  {
    id: "indusind-legend", slug: "indusind-legend", name: "Legend", bank: "IndusInd Bank", network: ["Visa"],
    category: "Rewards", tier: "Premium", color: "#7a288a",
    joiningFee: 0, annualFee: 0, annualFeeWaiver: 0,
    baseRate: 0.014, rewardCurrency: "Reward Points", pointValue: 0.7,
    rewardRules: [{ category: "dining", rate: 0.025 }, { category: "online", rate: 0.02 }],
    minIncomeAnnual: 1000000, minCreditScore: 750, minAge: 21,
    loungeVisitsDomestic: 4, loungeVisitsIntl: 0, forexMarkup: 3.5,
    welcomeBonusValue: 0, welcomeBonusDesc: "Lifetime free (relationship-based).",
    benefits: ["Lifetime free", "Weekend dining bonus", "Concierge"],
    bestFor: ["No-fee premium", "Dining"],
    summary: "A relationship-based lifetime-free premium card with weekend dining bonuses and a good point value.",
    pros: ["No fee", "Good point value", "Concierge"],
    cons: ["Relationship-gated", "Limited lounge"],
  },
  {
    id: "axis-flipkart-super-elite", slug: "axis-airtel", name: "Airtel Axis", bank: "Axis Bank", network: ["Visa"],
    category: "Cashback", tier: "Entry", color: "#e40000",
    joiningFee: 500, annualFee: 500, annualFeeWaiver: 200000,
    baseRate: 0.01, rewardCurrency: "Cashback", pointValue: 1,
    rewardRules: [{ category: "bills", rate: 0.25, monthlyCapValue: 250 }, { category: "online", rate: 0.01 }],
    minIncomeAnnual: 300000, minCreditScore: 700, minAge: 18,
    loungeVisitsDomestic: 0, loungeVisitsIntl: 0, forexMarkup: 3.5,
    welcomeBonusValue: 500, welcomeBonusDesc: "Amazon voucher on joining.",
    benefits: ["25% cashback on Airtel bills/recharge", "10% on Swiggy/Zomato/BigBasket", "1% elsewhere"],
    bestFor: ["Airtel users", "Bill payments"],
    summary: "Outsized 25% cashback on Airtel recharges and bills (capped), ideal if your utilities run through Airtel.",
    pros: ["Very high bill cashback", "Good food delivery reward"],
    cons: ["Bonus capped at ₹250/mo", "Value tied to Airtel"],
  },
  {
    id: "icici-coral", slug: "icici-coral", name: "Coral", bank: "ICICI Bank", network: ["Visa", "RuPay"],
    category: "Rewards", tier: "Entry", color: "#fb7185",
    joiningFee: 500, annualFee: 500, annualFeeWaiver: 150000,
    baseRate: 0.005, rewardCurrency: "Reward Points", pointValue: 0.25,
    rewardRules: [{ category: "dining", rate: 0.01 }, { category: "groceries", rate: 0.01 }],
    minIncomeAnnual: 300000, minCreditScore: 700, minAge: 18,
    loungeVisitsDomestic: 4, loungeVisitsIntl: 0, forexMarkup: 3.5,
    welcomeBonusValue: 0, welcomeBonusDesc: "Low fee with waiver.",
    benefits: ["BookMyShow 25% off", "Quarterly lounge access", "Fuel surcharge waiver"],
    bestFor: ["Entry users", "Movie buffs"],
    summary: "A popular entry ICICI card with movie discounts and quarterly lounge access at a low fee.",
    pros: ["Movie benefits", "Lounge at low fee", "Easy approval"],
    cons: ["Low base reward", "Modest point value"],
  },
  {
    id: "hdfc-swiggy", slug: "hdfc-swiggy", name: "Swiggy HDFC", bank: "HDFC Bank", network: ["Mastercard"],
    category: "Co-brand", tier: "Entry", color: "#fc8019",
    joiningFee: 500, annualFee: 500, annualFeeWaiver: 200000,
    baseRate: 0.01, rewardCurrency: "Cashback", pointValue: 1,
    rewardRules: [{ category: "dining", rate: 0.1, monthlyCapValue: 1500 }, { category: "online", rate: 0.05 }, { category: "groceries", rate: 0.05 }],
    minIncomeAnnual: 300000, minCreditScore: 720, minAge: 21,
    loungeVisitsDomestic: 0, loungeVisitsIntl: 0, forexMarkup: 3.5,
    welcomeBonusValue: 900, welcomeBonusDesc: "3 months Swiggy One membership.",
    benefits: ["10% cashback on Swiggy", "5% on online spends", "Swiggy One membership"],
    bestFor: ["Food delivery", "Swiggy regulars"],
    summary: "10% cashback across the Swiggy app (food, Instamart, Dineout) — the go-to card for food-delivery-heavy users.",
    pros: ["High Swiggy cashback", "Broad 5% online", "Free Swiggy One"],
    cons: ["Bonus capped monthly", "Value tied to Swiggy"],
  },
  {
    id: "federal-celesta", slug: "federal-celesta", name: "Celesta", bank: "Federal Bank", network: ["Visa"],
    category: "Premium", tier: "Premium", color: "#114b5f",
    joiningFee: 3000, annualFee: 3000, annualFeeWaiver: 500000,
    baseRate: 0.02, rewardCurrency: "Reward Points", pointValue: 0.25,
    rewardRules: [{ category: "dining", rate: 0.04 }, { category: "travel", rate: 0.04 }],
    minIncomeAnnual: 1500000, minCreditScore: 750, minAge: 21,
    loungeVisitsDomestic: 12, loungeVisitsIntl: 4, forexMarkup: 2,
    welcomeBonusValue: 3000, welcomeBonusDesc: "Welcome reward points.",
    benefits: ["Accelerated travel & dining", "Lounge access", "Concierge"],
    bestFor: ["Premium travel", "Federal customers"],
    summary: "Federal Bank's premium travel-and-dining card with a solid lounge stack and concierge.",
    pros: ["Good travel/dining", "Lounge access", "Fee waiver achievable"],
    cons: ["Smaller network/acceptance", "Modest point value"],
  },
  {
    id: "bob-eterna", slug: "bob-eterna", name: "Eterna", bank: "Bank of Baroda", network: ["Visa"],
    category: "Rewards", tier: "Mid", color: "#f37021",
    joiningFee: 2499, annualFee: 2499, annualFeeWaiver: 200000,
    baseRate: 0.0075, rewardCurrency: "Reward Points", pointValue: 0.25,
    rewardRules: [{ category: "online", rate: 0.0375 }, { category: "dining", rate: 0.0375 }, { category: "travel", rate: 0.0375 }],
    minIncomeAnnual: 500000, minCreditScore: 730, minAge: 21,
    loungeVisitsDomestic: 8, loungeVisitsIntl: 0, forexMarkup: 2,
    welcomeBonusValue: 2500, welcomeBonusDesc: "Welcome reward points worth ₹2,500.",
    benefits: ["15 points/₹100 on online, dining, travel", "Lounge access", "Low forex"],
    bestFor: ["Mid spenders", "Online & dining"],
    summary: "A value mid-tier card with 5x earning on online, dining and travel, plus lounge access.",
    pros: ["Broad 5x earning", "Lounge access", "Low forex"],
    cons: ["Modest point value", "Lower brand recognition"],
  },
];

export const ARTICLES = [
  {
    slug: "what-is-a-credit-score",
    title: "What is a credit score, and why does it decide your cards?",
    category: "Credit scores",
    readMins: 5,
    excerpt: "A plain-English guide to CIBIL scores: what moves them, what doesn't, and the score you need for the cards you want.",
    body: `Your credit score is a three-digit summary of how reliably you repay borrowed money. In India the most cited score is CIBIL, ranging 300–900. Lenders read it as a risk signal: the higher the number, the lower the perceived risk, and the better the cards and rates you can access.

Five things move your score: payment history (the biggest factor — never miss a due date), credit utilisation (try to stay under 30% of your limit), the age of your accounts, your mix of credit types, and how often you apply for new credit. Hard enquiries from multiple applications in a short window can dent your score temporarily.

What does NOT affect it: checking your own score (a soft enquiry), your income on its own, or your savings balance. Entry cards typically want 700+, premium cards 750+, and super-premium cards 770+. If you are below those, the fastest lever is almost always lowering utilisation and clearing dues on time for a few cycles.`,
  },
  {
    slug: "annual-fee-worth-it",
    title: "Is the annual fee worth it? A simple break-even rule",
    category: "Credit cards",
    readMins: 4,
    excerpt: "Stop guessing. Here's the one calculation that tells you whether a paid card earns its keep.",
    body: `A paid card is worth it only if the value you extract exceeds the fee you pay. The break-even rule: estimate your annual reward value at the card's rates for your real spending, add the rupee value of perks you will actually use (lounge visits, memberships), and subtract the net annual fee.

If that number is positive, the fee is justified. The trap is counting perks you won't use — a card with eight lounge visits is worth nothing extra if you fly twice a year and already have lounge access elsewhere. Be honest about the perks you'll redeem.

Many cards also waive the fee above a spend threshold. If you'll clear it comfortably, treat the effective fee as zero in your maths. CreditWise's reward calculator does this break-even automatically against the figures you enter.`,
  },
  {
    slug: "common-credit-card-mistakes",
    title: "Seven credit card mistakes that quietly cost you",
    category: "Common mistakes",
    readMins: 6,
    excerpt: "Revolving balances, chasing sign-ups, ignoring caps — the habits that erase your rewards.",
    body: `One: revolving a balance. Interest at 36–42% annually dwarfs any reward you earn — always pay the full statement, not the minimum. Two: chasing welcome bonuses for cards that don't fit your spending. Three: ignoring monthly reward caps; a "5%" card capped at ₹1,000/month is only 5% up to ₹20,000 of spend.

Four: using one card for everything when a second card would earn far more in a category. Five: letting points expire — most have a 2–3 year life. Six: missing the fee-waiver threshold by a small margin. Seven: applying for many cards at once, which stacks hard enquiries and dents your score.

The fix for all seven is a small amount of structure: know your top spend categories, match a card to each, automate full payments, and review once a year.`,
  },
  {
    slug: "building-credit-responsibly",
    title: "Using credit responsibly when you're just starting out",
    category: "Financial responsibility",
    readMins: 5,
    excerpt: "How to build a strong credit history from your first card without falling into debt.",
    body: `Your first card is a tool for building history, not spending power. Start with a lifetime-free or low-fee card you'll be approved for, and use it for regular, budgeted spends you'd make anyway — a subscription, fuel, groceries.

Set up autopay for the full statement amount from day one. This single habit protects your payment history, the largest driver of your score, and means you never pay interest. Keep utilisation low: if your limit is ₹50,000, try to keep the statement balance under ₹15,000.

Resist the urge to collect cards early. One card used well for 6–12 months builds more credit health than three cards used carelessly. Once your score crosses 750 and your spends justify it, you can add a category-specific second card — and that's exactly when a tool like CreditWise earns its place.`,
  },
];
