import type { CreditCard } from "./types";

// Cards added from official issuer pages checked on 2026-09-15.
// Only issuer-published benefits/fees are used here; unknown eligibility fields are left broad.
export const VERIFIED_CARDS: CreditCard[] = [
  {
    id: "hdfc-pixel-play",
    slug: "hdfc-pixel-play",
    name: "PIXEL Play",
    bank: "HDFC Bank",
    network: ["Visa", "RuPay"],
    category: "Shopping",
    tier: "Entry",
    color: "#111827",
    joiningFee: 500,
    annualFee: 500,
    annualFeeWaiver: 100000,
    baseRate: 0.01,
    rewardRules: [
      { category: "dining", rate: 0.05 },
      { category: "entertainment", rate: 0.05 },
      { category: "travel", rate: 0.05 },
      { category: "groceries", rate: 0.05 },
      { category: "online", rate: 0.03 },
      { category: "upi", rate: 0.01 },
    ],
    rewardCurrency: "Cashback",
    pointValue: 1,
    minIncomeAnnual: 300000,
    minCreditScore: 0,
    minAge: 18,
    loungeVisitsDomestic: 0,
    loungeVisitsIntl: 0,
    forexMarkup: 3.5,
    welcomeBonusValue: 0,
    welcomeBonusDesc: "Customisable card and billing cycle.",
    benefits: ["5% cashback on any two chosen packs", "3% cashback on Amazon, Flipkart or PayZapp", "1% cashback on UPI with RuPay"],
    bestFor: ["Customised rewards", "Shopping", "Dining & entertainment"],
    summary: "A choose-your-own-rewards card: select two 5% cashback packs across dining, travel, grocery, electronics or fashion.",
    pros: ["Choose two preferred 5% categories", "Customisable design and billing cycle", "UPI cashback on RuPay"],
    cons: ["Only two 5% packs can be selected", "3.5% foreign transaction fee"],
    verified: true,
    verifiedOn: "2026-09-15",
    officialUrl: "https://www.hdfc.bank.in/credit-cards/pixel-play-credit-card",
  },
  {
    id: "hdfc-swiggy",
    slug: "hdfc-swiggy",
    name: "Swiggy HDFC Bank Credit Card",
    bank: "HDFC Bank",
    network: ["Mastercard"],
    category: "Co-brand",
    tier: "Entry",
    color: "#ff5a3d",
    joiningFee: 500,
    annualFee: 500,
    annualFeeWaiver: 200000,
    baseRate: 0.01,
    rewardRules: [
      { category: "dining", rate: 0.10, monthlyCapValue: 1500 },
      { category: "groceries", rate: 0.10, monthlyCapValue: 1500 },
      { category: "online", rate: 0.05, monthlyCapValue: 1500 },
      { category: "other", rate: 0.01, monthlyCapValue: 500 },
    ],
    rewardCurrency: "Cashback",
    pointValue: 1,
    minIncomeAnnual: 180000,
    minCreditScore: 0,
    minAge: 18,
    loungeVisitsDomestic: 0,
    loungeVisitsIntl: 0,
    forexMarkup: 3.5,
    welcomeBonusValue: 0,
    welcomeBonusDesc: "3 months Swiggy One membership on activation.",
    benefits: ["10% cashback on eligible Swiggy app spends", "5% cashback on eligible online categories", "3 months Swiggy One membership"],
    bestFor: ["Swiggy users", "Food delivery", "Instamart"],
    summary: "A high-cashback card for Swiggy spending, with 10% cashback on eligible Swiggy app transactions and 5% on selected online categories.",
    pros: ["10% Swiggy cashback", "5% selected online cashback", "Low ₹500 annual fee"],
    cons: ["Category caps apply", "Several spend exclusions"],
    verified: true,
    verifiedOn: "2026-09-15",
    officialUrl: "https://www.hdfc.bank.in/credit-cards/swiggy-hdfc-bank-credit-card",
  },
  {
    id: "airtel-axis",
    slug: "airtel-axis",
    name: "Airtel Axis Bank",
    bank: "Axis Bank",
    network: ["Mastercard"],
    category: "Co-brand",
    tier: "Entry",
    color: "#e40000",
    joiningFee: 500,
    annualFee: 500,
    annualFeeWaiver: 200000,
    baseRate: 0.01,
    rewardRules: [
      { category: "bills", rate: 0.25 },
      { category: "other", rate: 0.01 },
    ],
    rewardCurrency: "Cashback",
    pointValue: 1,
    minIncomeAnnual: 0,
    minCreditScore: 0,
    minAge: 18,
    loungeVisitsDomestic: 0,
    loungeVisitsIntl: 0,
    forexMarkup: 3.5,
    welcomeBonusValue: 250,
    welcomeBonusDesc: "₹250 Amazon e-voucher on first transaction within 30 days, subject to offer terms.",
    benefits: ["25% cashback on eligible Airtel bills via Airtel Thanks", "10% cashback on eligible utility bills via Airtel Thanks", "10% value back at Zomato, Blinkit and District Movies"],
    bestFor: ["Airtel customers", "Utility bills", "Everyday cashback"],
    summary: "A co-branded cashback card built around Airtel bills, utilities and selected partner merchants.",
    pros: ["25% Airtel bill cashback", "10% utility cashback", "₹500 annual fee with ₹2L waiver"],
    cons: ["Best value is ecosystem-specific", "Caps and exclusions apply"],
    verified: true,
    verifiedOn: "2026-09-15",
    officialUrl: "https://www.axis.bank.in/cards/credit-card/airtel-axis-bank-credit-card",
  },
  {
    id: "axis-cashback",
    slug: "axis-cashback",
    name: "Cashback Credit Card",
    bank: "Axis Bank",
    network: ["Visa"],
    category: "Cashback",
    tier: "Mid",
    color: "#97144d",
    joiningFee: 1000,
    annualFee: 1000,
    annualFeeWaiver: 400000,
    baseRate: 0.0075,
    rewardRules: [
      { category: "online", rate: 0.07 },
      { category: "bills", rate: 0.005, monthlyCapValue: 100 },
      { category: "travel", rate: 0.0075 },
    ],
    rewardCurrency: "Cashback",
    pointValue: 1,
    minIncomeAnnual: 0,
    minCreditScore: 0,
    minAge: 18,
    loungeVisitsDomestic: 0,
    loungeVisitsIntl: 0,
    forexMarkup: 3.5,
    welcomeBonusValue: 1000,
    welcomeBonusDesc: "₹1,000 EDGE Reward points on first transaction within 30 days.",
    benefits: ["Up to 7% cashback on online spends", "0.75% base cashback on offline and travel spends", "Automatic cashback credit"],
    bestFor: ["Online spenders", "Cashback seekers", "High online spend"],
    summary: "A tiered cashback card that reaches 7% on higher monthly online spend, with 0.75% base cashback elsewhere.",
    pros: ["Up to 7% online cashback", "0.75% base cashback", "Automatic cashback redemption"],
    cons: ["Higher cashback requires higher monthly spend", "₹1,000 annual fee"],
    verified: true,
    verifiedOn: "2026-09-15",
    officialUrl: "https://www.axis.bank.in/cards/credit-card/cashback-credit-card",
  },
  {
    id: "scapia-axis",
    slug: "scapia-axis",
    name: "Scapia Axis Bank",
    bank: "Axis Bank",
    network: ["Mastercard", "RuPay"],
    category: "Travel",
    tier: "Mid",
    color: "#171717",
    joiningFee: 0,
    annualFee: 0,
    annualFeeWaiver: 0,
    baseRate: 0.10,
    rewardRules: [
      { category: "travel", rate: 0.20 },
      { category: "online", rate: 0.10 },
      { category: "other", rate: 0.10 },
      { category: "upi", rate: 0.05 },
    ],
    rewardCurrency: "Scapia Coins",
    pointValue: 1,
    minIncomeAnnual: 0,
    minCreditScore: 0,
    minAge: 18,
    loungeVisitsDomestic: 0,
    loungeVisitsIntl: 0,
    forexMarkup: 0,
    welcomeBonusValue: 0,
    welcomeBonusDesc: "Zero joining and annual fee.",
    benefits: ["20% Scapia Coins on eligible Scapia app travel bookings", "10% Scapia Coins on eligible Mastercard spends", "Zero forex markup"],
    bestFor: ["Frequent travellers", "International spends", "Zero-fee travel"],
    summary: "A zero-fee travel card with 20% Scapia Coins on eligible Scapia bookings, 10% on eligible Mastercard spends and zero forex markup.",
    pros: ["Zero annual fee", "Zero forex markup", "Strong travel rewards"],
    cons: ["Rewards are tied to Scapia Coins and redemption ecosystem", "Travel benefits depend on eligibility and spend conditions"],
    verified: true,
    verifiedOn: "2026-09-15",
    officialUrl: "https://www.axis.bank.in/cards/credit-card/scapia-axis-bank-credit-card",
  },
];
